TAREA
```{r}
c(1,2,3)
numeric_vector <- c(1,2,3)
class(numeric_vector)

character_vector <- c("a","b","c")
boolean_vector <- c(TRUE, FALSE, TRUE)
class(boolean_vector)
```
Matis 5x5
```{r}
peso_mes1 <- c(160, 164.3, 178.4, 190.4, 175)
peso_mes2 <- c(161, 164.1, 178.0, 190.4, 175.7)
peso_mes3 <- c(162, 164.7, 178.6, 190.7, 176)
peso_mes4 <- c(160, 163.3, 175.6, 191.4, 174.3)
peso_mes5 <- c(161, 162.3, 174.4, 188.5, 173.3)

peso_mensual <- c(peso_mes1, peso_mes2, peso_mes3, peso_mes4, peso_mes5)

control_peso <- matrix(peso_mensual, byrow = TRUE, nrow = 5)

meses <- c("Enero", "Febrero", "Marzo", "Abril", "Mayo")
personas <- c("Pedro", "Jose", "Juan", "María", "Sofía")
colnames(control_peso) <- meses
rownames(control_peso) <- personas
control_peso

#Media
install.packages("matrixStats")
library(matrixStats)

rowSums(control_peso/5)

PromedioXpersona <- rowSums(control_peso/5)
promedioMensual <- colSums(control_peso/5)
control_final <- cbind(control_peso, PromedioXpersona)

Control_peso_mensual <- rbind(control_final, promedioMensual)
Control_peso_mensual

```

Clase de Functions
```{r}
pow_two <- function(x){
  y <- x^2
  return(y)
}
 pow_two(4)
 
 
 pow_two <- function(x, print_info=TRUE){
   y <- x^2
   if(print_info){
     print(paste(x,"To the power two equals", y))
   }
   return(y)
 }
 pow_two(3)
 
```


