HOMEWORK 4

```{r}
library(dplyr)
library(ggplot2)
diamonds <- read.csv(file.choose(), header = TRUE, sep = ",")
```
1. Dispersión
```{r}
#1.1. Construya un gráfico de dispersión colocando en la estética carat (eje x) versus price (eje y), luego devuelva el gráfico.

ggplot(diamonds, aes(x=carat, y=price)) +
  geom_point()

#1.2. Edite la estética y mapee el color con la variable clarity.

ggplot(diamonds, aes(x=carat, y=price, color=clarity)) +
  geom_point()

```
2. Histograma
```{r}
#2.1. Construya el tipo de geometría histograma para la variable price. Configure el parámetro bins con el valor 40 y devuelva el gráfico.
ggplot(diamonds, aes(x=price)) +
  geom_histogram(bins=40)

#2.2. Agregue una escala logarítmica de base 10 y devuelva el gráfico para ver la diferencia.
ggplot(diamonds, aes(x=price)) +
  geom_histogram(bins=40) + 
  scale_x_log10()

```
3. Boxplots
```{r}
#3.1. Construya un gráfico de cajas colocando en la estética la variable cut (eje x)
#versus price (eje y). Agregue una escala logarítmica por defecto y por último
#devuelva el gráfico.

ggplot(diamonds, aes(x=cut, y=price)) +
  geom_boxplot() +
  scale_y_log10() 

#3.2. Edite el color de cada caja con el parámetro fill dentro de la estética y asignando
#la variable cut. Por último devuelva el gráfico.

ggplot(diamonds, aes(x=cut, y=price, fill = cut)) +
  geom_boxplot() +
  scale_y_log10() 

```
4. Faceting
```{r}
#4.1. Filtre diamonds por la variable price que sea mayor a 1000 y por cut que contenga las categorías Good, Ideal y Premium. Luego asigne el resultado a la
#variable filtered_price. Dado que cut debe tomar en cuenta tres categorías específicas puede hacer uso del pipe %in% , a continuación un ejemplo de su uso:
filtered_price <- diamonds %>%
  filter(price > 1000 & cut %in% c("Good", "Ideal", "Premium"))

ggplot(filtered_price, aes(x=cut, y=depth, fill=clarity)) +
  geom_col() +
  facet_wrap(~ clarity)

```
Grouping and summarizing

```{r}
#1. Utilice diamonds para construir un agrupamiento por la variable cut, luego aplique ummarize para encontrar la media de las variables x, y, z (los nombres de los valores umarizados serán mediaX, mediaY, mediaZ, respectivamente). Asigne el resultado a la ariable median_dimension_diamond, por último imprima la variable.

 median_dimension_diamond <- diamonds %>%
  group_by(cut) %>%
  summarise(mediaX = mean(x), mediaY = mean(y), mediaZ=mean(z))

 median_dimension_diamond

#. Utilice diamonds para filtrar por la variable cut igual a Premium. Luego agrupe por la ariable clarity y utilice summarize para encontrar minimo y maximo de price (los nombres de los valores sumarizados serán minPrice y maxPrice, respectivamente). Asigne el resultado a la variable cut_premium e imprima el valor de la variable.

cut_premium <- diamonds %>%
  filter(cut == "Premium") %>%
  group_by(clarity) %>%
  summarise(minPrice = min(price), maxPrice =max(price))

cut_premium

#3. Construya un gráfico de barras y utilice cut_premium como set de datos, configure =clarity, y=maxPrice y el color de relleno (fill) con la variable clarity. Por último evuelva el gráfico.

ggplot(cut_premium, aes(x=clarity, y=maxPrice, fill=clarity)) +
  geom_col()

```






